### ISSUE TITLE
[TSK-283] Incorporate new naming schemes from twitter and sentinel scrapers for v2 launch

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/mpi-sda-augmentation#2]
The new naming schemes introduced in 
https://github.com/dream-aim-deliver/mpi-sda-twitter-scraper/issues/7
https://github.com/dream-aim-deliver/mpi-sda-sentinel/issues/8

must be adapted within the augmentation repo

**Comment by Deeptikandhol10** [comment]
@sk-ram , whats the status of this activity?

**Comment by maany** [comment]
Closed in #3
